# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'macro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1020, 1308)
        self.check_mouse_position_button = QtWidgets.QPushButton(Dialog)
        self.check_mouse_position_button.setGeometry(QtCore.QRect(80, 980, 401, 131))
        self.check_mouse_position_button.setObjectName("check_mouse_position_button")
        self.mouse_position_label = QtWidgets.QLabel(Dialog)
        self.mouse_position_label.setGeometry(QtCore.QRect(90, 20, 831, 101))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.mouse_position_label.setFont(font)
        self.mouse_position_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mouse_position_label.setObjectName("mouse_position_label")
        self.click_saved_position_button = QtWidgets.QPushButton(Dialog)
        self.click_saved_position_button.setGeometry(QtCore.QRect(510, 1150, 401, 131))
        self.click_saved_position_button.setObjectName("click_saved_position_button")
        self.click_saved_position_button_2 = QtWidgets.QPushButton(Dialog)
        self.click_saved_position_button_2.setGeometry(QtCore.QRect(510, 980, 401, 131))
        self.click_saved_position_button_2.setObjectName("click_saved_position_button_2")
        self.time_click_button = QtWidgets.QPushButton(Dialog)
        self.time_click_button.setGeometry(QtCore.QRect(80, 1150, 401, 131))
        self.time_click_button.setObjectName("time_click_button")
        self.time_textEdit = QtWidgets.QTextEdit(Dialog)
        self.time_textEdit.setGeometry(QtCore.QRect(80, 509, 831, 71))
        self.time_textEdit.setObjectName("time_textEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 430, 811, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(100, 140, 811, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.memory_profile_edit = QtWidgets.QTextEdit(Dialog)
        self.memory_profile_edit.setGeometry(QtCore.QRect(90, 210, 831, 71))
        self.memory_profile_edit.setObjectName("memory_profile_edit")
        self.check_memory_profile_button = QtWidgets.QPushButton(Dialog)
        self.check_memory_profile_button.setGeometry(QtCore.QRect(90, 290, 831, 131))
        self.check_memory_profile_button.setObjectName("check_memory_profile_button")
        self.screnn_shot_time_textEdit = QtWidgets.QTextEdit(Dialog)
        self.screnn_shot_time_textEdit.setGeometry(QtCore.QRect(80, 859, 831, 71))
        self.screnn_shot_time_textEdit.setObjectName("screnn_shot_time_textEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(80, 780, 811, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.select_directory_button = QtWidgets.QPushButton(Dialog)
        self.select_directory_button.setGeometry(QtCore.QRect(80, 690, 831, 81))
        self.select_directory_button.setObjectName("select_directory_button")
        self.directory_label = QtWidgets.QLabel(Dialog)
        self.directory_label.setGeometry(QtCore.QRect(80, 600, 811, 71))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.directory_label.setFont(font)
        self.directory_label.setObjectName("directory_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.check_mouse_position_button.setText(_translate("Dialog", "마우스 위치 확인 (F3)"))
        self.mouse_position_label.setText(_translate("Dialog", "마우스 위치"))
        self.click_saved_position_button.setText(_translate("Dialog", "마우스 저장 위치 클릭 (F6)"))
        self.click_saved_position_button_2.setText(_translate("Dialog", "중지 (F4)"))
        self.time_click_button.setText(_translate("Dialog", "시간 반복 (F5)"))
        self.label.setText(_translate("Dialog", "마우스 클릭 반복 시간 (초)"))
        self.label_2.setText(_translate("Dialog", "메모리 프로파일 위치"))
        self.check_memory_profile_button.setText(_translate("Dialog", "프로파일 경로 설정"))
        self.label_3.setText(_translate("Dialog", "스크린 샷 반복 시간 (초)"))
        self.select_directory_button.setText(_translate("Dialog", "스크린 샷 위치 설정"))
        self.directory_label.setText(_translate("Dialog", "스크린샷 경로"))
